server:
#  port: 9001
  # port ? 0?? ??? ?? ??? ? ?? ?? port? ????.
  port: 0

spring:
  application:
    name: user-service
eureka:
  client:
    # ??? ??? ??? ?????? true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka # ??? ??
  instance:
    # port? 0?? ???? eureka ????? ?? ??? 0??? ???? ??? ?? ?? ??? ???. ??? ??? ???? ?? ??? ??
    # ??? Eureka ? UI? ???? ?????? ??? url? ???? ??? ????? ???
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}


